-- ============================================================
-- Talk2Learn — Vocabulary Cards A1 (500 слов)
-- Темы: Animals, Food, Drinks, Home, Colors, Numbers,
--        Family, Body, Clothes, Weather, Time, Nature,
--        School, Transport, Places, Greetings, Actions, Adjectives
-- Формат: (topic, level, word, translation, definition, emoji_code, order_num)
-- ============================================================

INSERT INTO vocabulary_cards (topic, level, word, translation, definition, emoji_code, order_num) VALUES

-- ============================================================
-- ANIMALS (30 слов)
-- ============================================================
('Animals','A1','cat','кот / кошка','A small pet that says meow','🐱',1),
('Animals','A1','dog','собака','A loyal pet animal','🐶',2),
('Animals','A1','bird','птица','An animal with wings that can fly','🐦',3),
('Animals','A1','fish','рыба','An animal that lives in water','🐟',4),
('Animals','A1','horse','лошадь','A large animal used for riding','🐴',5),
('Animals','A1','cow','корова','A farm animal that gives milk','🐄',6),
('Animals','A1','pig','свинья','A pink farm animal','🐷',7),
('Animals','A1','sheep','овца','A farm animal with wool','🐑',8),
('Animals','A1','rabbit','кролик','A small animal with long ears','🐰',9),
('Animals','A1','duck','утка','A bird that swims in water','🦆',10),
('Animals','A1','bear','медведь','A large wild animal','🐻',11),
('Animals','A1','lion','лев','The king of the jungle','🦁',12),
('Animals','A1','elephant','слон','A very large animal with a trunk','🐘',13),
('Animals','A1','monkey','обезьяна','An animal that climbs trees','🐒',14),
('Animals','A1','snake','змея','A long animal without legs','🐍',15),
('Animals','A1','frog','лягушка','A small green jumping animal','🐸',16),
('Animals','A1','tiger','тигр','A big wild cat with stripes','🐯',17),
('Animals','A1','wolf','волк','A wild dog-like animal','🐺',18),
('Animals','A1','fox','лиса','A clever wild orange animal','🦊',19),
('Animals','A1','mouse','мышь','A very small animal','🐭',20),
('Animals','A1','chicken','курица','A farm bird we eat eggs from','🐔',21),
('Animals','A1','penguin','пингвин','A black and white bird that cannot fly','🐧',22),
('Animals','A1','dolphin','дельфин','A smart sea animal','🐬',23),
('Animals','A1','turtle','черепаха','An animal with a hard shell','🐢',24),
('Animals','A1','bee','пчела','A yellow and black insect that makes honey','🐝',25),
('Animals','A1','butterfly','бабочка','A beautiful flying insect','🦋',26),
('Animals','A1','ant','муравей','A very small hard-working insect','🐜',27),
('Animals','A1','spider','паук','An eight-legged insect','🕷',28),
('Animals','A1','deer','олень','A wild animal with big horns','🦌',29),
('Animals','A1','hamster','хомяк','A small pet with big cheeks','🐹',30),

-- ============================================================
-- FOOD (35 слов)
-- ============================================================
('Food','A1','apple','яблоко','A round red or green fruit','🍎',1),
('Food','A1','banana','банан','A long yellow fruit','🍌',2),
('Food','A1','bread','хлеб','A baked food made from flour','🍞',3),
('Food','A1','egg','яйцо','Food from a chicken','🥚',4),
('Food','A1','rice','рис','Small white grains we cook and eat','🍚',5),
('Food','A1','soup','суп','Hot liquid food','🍲',6),
('Food','A1','pizza','пицца','Italian food with cheese and toppings','🍕',7),
('Food','A1','burger','бургер','A sandwich with a meat patty','🍔',8),
('Food','A1','cake','торт / пирог','A sweet baked dessert','🎂',9),
('Food','A1','salad','салат','A dish of mixed vegetables','🥗',10),
('Food','A1','cheese','сыр','A dairy product made from milk','🧀',11),
('Food','A1','butter','масло','A yellow fat made from cream','🧈',12),
('Food','A1','milk','молоко','A white liquid from cows','🥛',13),
('Food','A1','orange','апельсин','A round orange citrus fruit','🍊',14),
('Food','A1','lemon','лимон','A yellow sour citrus fruit','🍋',15),
('Food','A1','tomato','помидор','A red fruit used in cooking','🍅',16),
('Food','A1','potato','картофель','A starchy vegetable grown underground','🥔',17),
('Food','A1','carrot','морковь','An orange root vegetable','🥕',18),
('Food','A1','onion','лук','A round vegetable with layers','🧅',19),
('Food','A1','garlic','чеснок','A strong-smelling white bulb','🧄',20),
('Food','A1','pasta','паста / макароны','Italian noodles','🍝',21),
('Food','A1','sandwich','бутерброд','Two slices of bread with filling','🥪',22),
('Food','A1','ice cream','мороженое','A cold sweet dessert','🍦',23),
('Food','A1','chocolate','шоколад','A sweet brown food','🍫',24),
('Food','A1','cookie','печенье','A small sweet biscuit','🍪',25),
('Food','A1','honey','мёд','A sweet liquid made by bees','🍯',26),
('Food','A1','strawberry','клубника','A small red sweet fruit','🍓',27),
('Food','A1','grapes','виноград','Small round fruits that grow in clusters','🍇',28),
('Food','A1','watermelon','арбуз','A large green fruit with red inside','🍉',29),
('Food','A1','mushroom','гриб','A fungus used in cooking','🍄',30),
('Food','A1','corn','кукуруза','A yellow vegetable on a cob','🌽',31),
('Food','A1','pepper','перец','A spicy or sweet vegetable','🌶',32),
('Food','A1','cucumber','огурец','A long green vegetable','🥒',33),
('Food','A1','meat','мясо','Food from animals','🥩',34),
('Food','A1','fish','рыба (еда)','Seafood eaten as a meal','🐟',35),

-- ============================================================
-- DRINKS (15 слов)
-- ============================================================
('Drinks','A1','water','вода','A clear liquid essential for life','💧',1),
('Drinks','A1','tea','чай','A hot drink made with leaves','☕',2),
('Drinks','A1','coffee','кофе','A hot dark drink','☕',3),
('Drinks','A1','juice','сок','A drink made from fruit','🧃',4),
('Drinks','A1','cola','кола','A sweet fizzy dark drink','🥤',5),
('Drinks','A1','lemonade','лимонад','A sweet lemon drink','🍋',6),
('Drinks','A1','beer','пиво','An alcoholic drink made from grain','🍺',7),
('Drinks','A1','wine','вино','An alcoholic drink made from grapes','🍷',8),
('Drinks','A1','smoothie','смузи','A blended fruit drink','🥤',9),
('Drinks','A1','milkshake','молочный коктейль','A thick sweet milk drink','🥛',10),
('Drinks','A1','hot chocolate','горячий шоколад','A warm sweet cocoa drink','☕',11),
('Drinks','A1','soda','газировка','A fizzy sweet drink','🥤',12),
('Drinks','A1','yogurt','йогурт','A thick dairy drink or food','🥛',13),
('Drinks','A1','champagne','шампанское','A fizzy white wine for celebrations','🍾',14),
('Drinks','A1','syrup','сироп','A thick sweet liquid added to drinks','🍯',15),

-- ============================================================
-- HOME (30 слов)
-- ============================================================
('Home','A1','house','дом','A building where people live','🏠',1),
('Home','A1','room','комната','A space inside a building','🚪',2),
('Home','A1','kitchen','кухня','A room for cooking','🍳',3),
('Home','A1','bedroom','спальня','A room for sleeping','🛏',4),
('Home','A1','bathroom','ванная','A room with a bath or shower','🛁',5),
('Home','A1','door','дверь','An entrance to a room','🚪',6),
('Home','A1','window','окно','A glass opening in a wall','🪟',7),
('Home','A1','table','стол','A flat surface with legs','🪑',8),
('Home','A1','chair','стул','Furniture for sitting','🪑',9),
('Home','A1','bed','кровать','Furniture for sleeping','🛏',10),
('Home','A1','sofa','диван','A comfortable seat for several people','🛋',11),
('Home','A1','lamp','лампа','A device that gives light','💡',12),
('Home','A1','clock','часы','A device that shows time','🕐',13),
('Home','A1','mirror','зеркало','A reflective surface','🪞',14),
('Home','A1','stairs','лестница','Steps connecting floors','🪜',15),
('Home','A1','floor','пол','The bottom surface of a room','🏠',16),
('Home','A1','wall','стена','A vertical surface in a room','🏠',17),
('Home','A1','ceiling','потолок','The top surface of a room','🏠',18),
('Home','A1','fridge','холодильник','A cold appliance for food storage','🧊',19),
('Home','A1','oven','духовка','An appliance for baking','🍳',20),
('Home','A1','TV','телевизор','An electronic screen for watching','📺',21),
('Home','A1','phone','телефон','A device for calling','📱',22),
('Home','A1','computer','компьютер','An electronic device for work','💻',23),
('Home','A1','book','книга','Pages with writing or pictures','📚',24),
('Home','A1','key','ключ','A metal object that opens locks','🔑',25),
('Home','A1','bag','сумка','A container for carrying things','👜',26),
('Home','A1','box','коробка','A square container','📦',27),
('Home','A1','cup','чашка','A container for drinking','☕',28),
('Home','A1','plate','тарелка','A flat dish for food','🍽',29),
('Home','A1','spoon','ложка','A utensil for eating soup','🥄',30),

-- ============================================================
-- COLORS (15 слов)
-- ============================================================
('Colors','A1','red','красный','The color of fire and blood','🔴',1),
('Colors','A1','blue','синий / голубой','The color of the sky','🔵',2),
('Colors','A1','green','зелёный','The color of grass','🟢',3),
('Colors','A1','yellow','жёлтый','The color of the sun','🟡',4),
('Colors','A1','orange','оранжевый','A warm color between red and yellow','🟠',5),
('Colors','A1','purple','фиолетовый','A mix of red and blue','🟣',6),
('Colors','A1','pink','розовый','A light red color','🩷',7),
('Colors','A1','black','чёрный','The darkest color','⚫',8),
('Colors','A1','white','белый','The lightest color','⚪',9),
('Colors','A1','grey','серый','A color between black and white','🩶',10),
('Colors','A1','brown','коричневый','The color of wood or chocolate','🟫',11),
('Colors','A1','gold','золотой','A shiny yellow metallic color','🌟',12),
('Colors','A1','silver','серебряный','A shiny grey metallic color','⭐',13),
('Colors','A1','light blue','светло-голубой','A pale blue color','🩵',14),
('Colors','A1','dark green','тёмно-зелёный','A deep green color','🌲',15),

-- ============================================================
-- FAMILY (20 слов)
-- ============================================================
('Family','A1','mother','мать / мама','A female parent','👩',1),
('Family','A1','father','отец / папа','A male parent','👨',2),
('Family','A1','sister','сестра','A female sibling','👧',3),
('Family','A1','brother','брат','A male sibling','👦',4),
('Family','A1','grandmother','бабушка','Mother of your parent','👵',5),
('Family','A1','grandfather','дедушка','Father of your parent','👴',6),
('Family','A1','daughter','дочь','A female child','👧',7),
('Family','A1','son','сын','A male child','👦',8),
('Family','A1','aunt','тётя','Your parent''s sister','👩',9),
('Family','A1','uncle','дядя','Your parent''s brother','👨',10),
('Family','A1','cousin','двоюродный брат/сестра','Child of your aunt or uncle','🧒',11),
('Family','A1','wife','жена','A married woman','👰',12),
('Family','A1','husband','муж','A married man','🤵',13),
('Family','A1','baby','малыш','A very young child','👶',14),
('Family','A1','child','ребёнок','A young person','🧒',15),
('Family','A1','parents','родители','Mother and father together','👨‍👩‍👦',16),
('Family','A1','family','семья','A group of related people','👨‍👩‍👧‍👦',17),
('Family','A1','twins','близнецы','Two children born at the same time','👶',18),
('Family','A1','nephew','племянник','Your sibling''s son','👦',19),
('Family','A1','niece','племянница','Your sibling''s daughter','👧',20),

-- ============================================================
-- BODY (25 слов)
-- ============================================================
('Body','A1','head','голова','The top part of the body','🗣',1),
('Body','A1','hair','волосы','Strands growing on the head','💇',2),
('Body','A1','eye','глаз','An organ used for seeing','👁',3),
('Body','A1','ear','ухо','An organ used for hearing','👂',4),
('Body','A1','nose','нос','An organ used for smelling','👃',5),
('Body','A1','mouth','рот','Used for eating and speaking','👄',6),
('Body','A1','tooth','зуб','A hard white structure in the mouth','🦷',7),
('Body','A1','tongue','язык','A muscle inside the mouth','👅',8),
('Body','A1','neck','шея','The part connecting head and body','🙆',9),
('Body','A1','shoulder','плечо','The top of the arm','💪',10),
('Body','A1','arm','рука (от плеча)','A limb from shoulder to hand','💪',11),
('Body','A1','hand','рука (кисть)','The end part of the arm','🤚',12),
('Body','A1','finger','палец','One of five digits on the hand','☝',13),
('Body','A1','leg','нога','A limb used for walking','🦵',14),
('Body','A1','foot','ступня','The bottom of the leg','🦶',15),
('Body','A1','knee','колено','The joint in the middle of the leg','🦵',16),
('Body','A1','back','спина','The rear part of the body','🙆',17),
('Body','A1','stomach','живот','The front middle of the body','🫃',18),
('Body','A1','chest','грудь','The front upper body','💪',19),
('Body','A1','heart','сердце','The organ that pumps blood','❤',20),
('Body','A1','face','лицо','The front of the head','😊',21),
('Body','A1','cheek','щека','The soft side of the face','😊',22),
('Body','A1','chin','подбородок','The bottom of the face','🙂',23),
('Body','A1','thumb','большой палец','The short wide finger','👍',24),
('Body','A1','nail','ноготь','The hard covering on a finger','💅',25),

-- ============================================================
-- CLOTHES (25 слов)
-- ============================================================
('Clothes','A1','shirt','рубашка','A top with buttons','👕',1),
('Clothes','A1','T-shirt','футболка','A casual top without buttons','👕',2),
('Clothes','A1','trousers','брюки','Long leg-covering clothes','👖',3),
('Clothes','A1','jeans','джинсы','Denim trousers','👖',4),
('Clothes','A1','dress','платье','A one-piece garment for women','👗',5),
('Clothes','A1','skirt','юбка','A garment worn below the waist','👗',6),
('Clothes','A1','jacket','куртка','An outer layer of clothing','🧥',7),
('Clothes','A1','coat','пальто','A long warm outer garment','🧥',8),
('Clothes','A1','shoes','туфли / обувь','Footwear for going outside','👟',9),
('Clothes','A1','boots','сапоги','Footwear covering the ankle','👢',10),
('Clothes','A1','socks','носки','Clothing for the feet','🧦',11),
('Clothes','A1','hat','шапка / шляпа','A covering for the head','🎩',12),
('Clothes','A1','scarf','шарф','A cloth worn around the neck','🧣',13),
('Clothes','A1','gloves','перчатки','Covering for hands','🧤',14),
('Clothes','A1','sweater','свитер','A warm knitted top','🧶',15),
('Clothes','A1','underwear','нижнее бельё','Clothes worn under other clothes','👙',16),
('Clothes','A1','pyjamas','пижама','Clothes worn for sleeping','🛏',17),
('Clothes','A1','uniform','форма','Special clothes for work or school','👔',18),
('Clothes','A1','suit','костюм','A formal jacket and trousers','👔',19),
('Clothes','A1','tie','галстук','A long piece of fabric around the neck','👔',20),
('Clothes','A1','belt','ремень','A strap worn around the waist','👖',21),
('Clothes','A1','pocket','карман','A small bag sewn into clothing','👖',22),
('Clothes','A1','button','пуговица','A small fastener on clothes','🔘',23),
('Clothes','A1','size','размер','How big or small something is','📏',24),
('Clothes','A1','colour','цвет (одежды)','The shade of a piece of clothing','🎨',25),

-- ============================================================
-- WEATHER (20 слов)
-- ============================================================
('Weather','A1','sun','солнце','The star that gives us light and heat','☀',1),
('Weather','A1','rain','дождь','Water falling from clouds','🌧',2),
('Weather','A1','snow','снег','White frozen water falling from clouds','❄',3),
('Weather','A1','cloud','облако','A white or grey mass in the sky','☁',4),
('Weather','A1','wind','ветер','Moving air','💨',5),
('Weather','A1','storm','буря / гроза','Very bad weather with heavy rain','⛈',6),
('Weather','A1','thunder','гром','A loud sound during a storm','⛈',7),
('Weather','A1','lightning','молния','A flash of light in a storm','⚡',8),
('Weather','A1','fog','туман','Very thick cloud near the ground','🌫',9),
('Weather','A1','ice','лёд','Frozen water','🧊',10),
('Weather','A1','rainbow','радуга','Coloured arch in the sky after rain','🌈',11),
('Weather','A1','temperature','температура','How hot or cold it is','🌡',12),
('Weather','A1','hot','жарко','Very high temperature','🥵',13),
('Weather','A1','cold','холодно','Very low temperature','🥶',14),
('Weather','A1','warm','тепло','A comfortable pleasant temperature','🌤',15),
('Weather','A1','cool','прохладно','Slightly cold but comfortable','🌬',16),
('Weather','A1','wet','мокро','Covered with water','💧',17),
('Weather','A1','dry','сухо','Without water or moisture','☀',18),
('Weather','A1','sunny','солнечно','Bright with sunshine','☀',19),
('Weather','A1','cloudy','облачно','Covered with clouds','☁',20),

-- ============================================================
-- TIME (20 слов)
-- ============================================================
('Time','A1','morning','утро','The early part of the day','🌅',1),
('Time','A1','afternoon','день / послеполудень','The middle of the day','☀',2),
('Time','A1','evening','вечер','The end of the day before night','🌆',3),
('Time','A1','night','ночь','The dark part of the day','🌙',4),
('Time','A1','today','сегодня','This current day','📅',5),
('Time','A1','tomorrow','завтра','The day after today','📅',6),
('Time','A1','yesterday','вчера','The day before today','📅',7),
('Time','A1','week','неделя','Seven days','📆',8),
('Time','A1','month','месяц','About 30 days','🗓',9),
('Time','A1','year','год','12 months','🗓',10),
('Time','A1','hour','час','60 minutes','⏰',11),
('Time','A1','minute','минута','60 seconds','⏱',12),
('Time','A1','second','секунда','A very short time','⏱',13),
('Time','A1','Monday','понедельник','The first day of the week','📅',14),
('Time','A1','Friday','пятница','The last working day','📅',15),
('Time','A1','weekend','выходные','Saturday and Sunday','🎉',16),
('Time','A1','holiday','праздник / каникулы','A special day or vacation','🎉',17),
('Time','A1','birthday','день рождения','The anniversary of your birth','🎂',18),
('Time','A1','now','сейчас','At this moment','⏰',19),
('Time','A1','late','поздно','After the expected time','🕐',20),

-- ============================================================
-- NATURE (20 слов)
-- ============================================================
('Nature','A1','tree','дерево','A tall plant with a trunk','🌳',1),
('Nature','A1','flower','цветок','A pretty plant with petals','🌸',2),
('Nature','A1','grass','трава','Green plants covering the ground','🌿',3),
('Nature','A1','river','река','A large stream of flowing water','🏞',4),
('Nature','A1','sea','море','A large body of salt water','🌊',5),
('Nature','A1','mountain','гора','A very high hill','⛰',6),
('Nature','A1','forest','лес','A large area of trees','🌲',7),
('Nature','A1','beach','пляж','Sand next to the sea','🏖',8),
('Nature','A1','sky','небо','The space above the earth','🌤',9),
('Nature','A1','star','звезда','A bright object in the night sky','⭐',10),
('Nature','A1','moon','луна','The natural satellite of Earth','🌕',11),
('Nature','A1','earth','земля','The ground or our planet','🌍',12),
('Nature','A1','sun','солнце','The star in our solar system','☀',13),
('Nature','A1','lake','озеро','A body of water surrounded by land','🏞',14),
('Nature','A1','island','остров','Land surrounded by water','🏝',15),
('Nature','A1','desert','пустыня','A very dry sandy area','🏜',16),
('Nature','A1','rock','камень / скала','A hard natural material','🪨',17),
('Nature','A1','sand','песок','Tiny grains found on beaches','🏖',18),
('Nature','A1','leaf','лист','The flat green part of a plant','🍃',19),
('Nature','A1','plant','растение','A living thing that grows in soil','🌱',20),

-- ============================================================
-- SCHOOL (25 слов)
-- ============================================================
('School','A1','school','школа','A place for learning','🏫',1),
('School','A1','teacher','учитель','A person who teaches','👩‍🏫',2),
('School','A1','student','ученик / студент','A person who learns','🧑‍🎓',3),
('School','A1','class','класс / урок','A group of students or a lesson','📚',4),
('School','A1','lesson','урок','A period of learning','📖',5),
('School','A1','book','книга','Pages bound together for reading','📚',6),
('School','A1','pen','ручка','A tool for writing with ink','🖊',7),
('School','A1','pencil','карандаш','A tool for writing that can be erased','✏',8),
('School','A1','paper','бумага','A thin material for writing','📄',9),
('School','A1','notebook','тетрадь','A book with blank pages for writing','📓',10),
('School','A1','bag','портфель / сумка','A container for carrying school things','🎒',11),
('School','A1','desk','парта / стол','A table for working or studying','🪑',12),
('School','A1','board','доска','A surface for writing in class','📋',13),
('School','A1','homework','домашнее задание','Work done at home for school','📝',14),
('School','A1','test','тест / контрольная','An exam to check knowledge','📝',15),
('School','A1','answer','ответ','A reply to a question','💬',16),
('School','A1','question','вопрос','Something you ask to get information','❓',17),
('School','A1','letter','буква / письмо','A symbol in the alphabet','🔤',18),
('School','A1','word','слово','A unit of language','💬',19),
('School','A1','number','число / номер','A symbol used in maths','🔢',20),
('School','A1','read','читать','To understand written words','📖',21),
('School','A1','write','писать','To form letters or words','✍',22),
('School','A1','listen','слушать','To pay attention to sound','👂',23),
('School','A1','speak','говорить','To say words aloud','🗣',24),
('School','A1','understand','понимать','To know the meaning','🧠',25),

-- ============================================================
-- TRANSPORT (20 слов)
-- ============================================================
('Transport','A1','car','машина','A vehicle with four wheels','🚗',1),
('Transport','A1','bus','автобус','A large vehicle for many passengers','🚌',2),
('Transport','A1','train','поезд','A vehicle that runs on rails','🚂',3),
('Transport','A1','plane','самолёт','A vehicle that flies','✈',4),
('Transport','A1','bicycle','велосипед','A two-wheeled vehicle you pedal','🚲',5),
('Transport','A1','taxi','такси','A car you pay to travel in','🚕',6),
('Transport','A1','boat','лодка','A small water vehicle','⛵',7),
('Transport','A1','ship','корабль','A large water vehicle','🚢',8),
('Transport','A1','motorcycle','мотоцикл','A two-wheeled motor vehicle','🏍',9),
('Transport','A1','truck','грузовик','A large vehicle for carrying goods','🚛',10),
('Transport','A1','tram','трамвай','An electric vehicle on city rails','🚃',11),
('Transport','A1','subway','метро','An underground train system','🚇',12),
('Transport','A1','helicopter','вертолёт','A flying vehicle with rotating blades','🚁',13),
('Transport','A1','road','дорога','A surface for vehicles to travel on','🛣',14),
('Transport','A1','street','улица','A road in a city with buildings','🏙',15),
('Transport','A1','station','станция / вокзал','A place where vehicles stop','🚉',16),
('Transport','A1','airport','аэропорт','A place where planes land','✈',17),
('Transport','A1','ticket','билет','A paper that lets you travel','🎫',18),
('Transport','A1','driver','водитель','A person who drives a vehicle','🧑‍✈️',19),
('Transport','A1','passenger','пассажир','A person travelling in a vehicle','🧳',20),

-- ============================================================
-- PLACES (20 слов)
-- ============================================================
('Places','A1','city','город','A large urban area','🏙',1),
('Places','A1','village','деревня','A small rural settlement','🏡',2),
('Places','A1','country','страна','A nation with its own government','🌍',3),
('Places','A1','shop','магазин','A place to buy things','🏪',4),
('Places','A1','market','рынок','An outdoor place to buy food','🛒',5),
('Places','A1','hospital','больница','A place where sick people are treated','🏥',6),
('Places','A1','bank','банк','A place to keep or borrow money','🏦',7),
('Places','A1','park','парк','An outdoor area for relaxing','🌳',8),
('Places','A1','restaurant','ресторан','A place to eat meals','🍽',9),
('Places','A1','café','кафе','A small place to drink coffee','☕',10),
('Places','A1','hotel','гостиница','A place to stay when travelling','🏨',11),
('Places','A1','library','библиотека','A place with books to borrow','📚',12),
('Places','A1','museum','музей','A place with historical objects','🏛',13),
('Places','A1','cinema','кинотеатр','A place to watch films','🎬',14),
('Places','A1','church','церковь','A place of worship','⛪',15),
('Places','A1','office','офис','A place where people work','🏢',16),
('Places','A1','factory','завод','A building where things are made','🏭',17),
('Places','A1','farm','ферма','A place where food is grown','🚜',18),
('Places','A1','zoo','зоопарк','A place with animals to visit','🦁',19),
('Places','A1','gym','спортзал','A place for exercise','🏋',20),

-- ============================================================
-- GREETINGS & PHRASES (20 слов)
-- ============================================================
('Greetings','A1','hello','привет / здравствуйте','A common greeting','👋',1),
('Greetings','A1','goodbye','пока / до свидания','Said when leaving','👋',2),
('Greetings','A1','please','пожалуйста','Used to make polite requests','🙏',3),
('Greetings','A1','thank you','спасибо','Said to show gratitude','🙏',4),
('Greetings','A1','sorry','извините / простите','Said to apologise','😔',5),
('Greetings','A1','yes','да','A positive answer','✅',6),
('Greetings','A1','no','нет','A negative answer','❌',7),
('Greetings','A1','OK','хорошо / ладно','Showing agreement','👍',8),
('Greetings','A1','help','помощь / помогите','Asking for assistance','🆘',9),
('Greetings','A1','welcome','добро пожаловать','A greeting to guests','🏠',10),
('Greetings','A1','good morning','доброе утро','A morning greeting','🌅',11),
('Greetings','A1','good night','спокойной ночи','Said before sleeping','🌙',12),
('Greetings','A1','how are you','как дела','Asking about someone''s wellbeing','😊',13),
('Greetings','A1','nice to meet you','приятно познакомиться','Said when meeting someone new','🤝',14),
('Greetings','A1','excuse me','извините','Used to get attention','🙋',15),
('Greetings','A1','I don''t understand','я не понимаю','Said when confused','😕',16),
('Greetings','A1','can you help me','вы можете помочь','Asking for help','🆘',17),
('Greetings','A1','what is your name','как вас зовут','Asking someone''s name','🙋',18),
('Greetings','A1','my name is','меня зовут','Introducing yourself','😊',19),
('Greetings','A1','see you later','до встречи','Informal goodbye','👋',20),

-- ============================================================
-- ACTIONS / VERBS (30 слов)
-- ============================================================
('Actions','A1','eat','есть / кушать','To put food in your mouth','🍴',1),
('Actions','A1','drink','пить','To consume liquid','💧',2),
('Actions','A1','sleep','спать','To rest with eyes closed','😴',3),
('Actions','A1','walk','ходить / гулять','To move on foot','🚶',4),
('Actions','A1','run','бегать / бежать','To move fast on foot','🏃',5),
('Actions','A1','sit','сидеть','To rest on a seat','🪑',6),
('Actions','A1','stand','стоять','To be upright on your feet','🧍',7),
('Actions','A1','look','смотреть','To direct your eyes at something','👀',8),
('Actions','A1','see','видеть','To perceive with eyes','👁',9),
('Actions','A1','hear','слышать','To perceive with ears','👂',10),
('Actions','A1','speak','говорить','To say words','🗣',11),
('Actions','A1','say','сказать','To express in words','💬',12),
('Actions','A1','come','приходить','To move towards a place','🚶',13),
('Actions','A1','go','идти / ехать','To move away from a place','🚶',14),
('Actions','A1','open','открывать','To make something not closed','🚪',15),
('Actions','A1','close','закрывать','To make something shut','🚪',16),
('Actions','A1','buy','покупать','To get something with money','🛒',17),
('Actions','A1','give','давать','To hand something to someone','🤝',18),
('Actions','A1','take','брать','To receive or pick up','🤚',19),
('Actions','A1','make','делать / готовить','To create or produce','🛠',20),
('Actions','A1','like','нравиться / любить','To enjoy something','❤',21),
('Actions','A1','want','хотеть','To desire something','💭',22),
('Actions','A1','need','нуждаться / нужно','To require something','📋',23),
('Actions','A1','work','работать','To do a job','💼',24),
('Actions','A1','play','играть','To have fun','🎮',25),
('Actions','A1','read','читать','To understand text','📖',26),
('Actions','A1','write','писать','To form letters','✍',27),
('Actions','A1','watch','смотреть (ТВ)','To observe something attentively','📺',28),
('Actions','A1','cook','готовить','To prepare food with heat','🍳',29),
('Actions','A1','clean','убирать / чистить','To make something tidy','🧹',30),

-- ============================================================
-- ADJECTIVES (25 слов)
-- ============================================================
('Adjectives','A1','big','большой','Of large size','🔵',1),
('Adjectives','A1','small','маленький','Of little size','🔹',2),
('Adjectives','A1','tall','высокий','Of great height','📏',3),
('Adjectives','A1','short','короткий / низкий','Not long or tall','📏',4),
('Adjectives','A1','long','длинный','Of great length','📏',5),
('Adjectives','A1','new','новый','Recently made or bought','✨',6),
('Adjectives','A1','old','старый','Having existed for a long time','🏚',7),
('Adjectives','A1','good','хороший','Of high quality','👍',8),
('Adjectives','A1','bad','плохой','Of low quality','👎',9),
('Adjectives','A1','happy','счастливый','Feeling pleased','😊',10),
('Adjectives','A1','sad','грустный','Feeling unhappy','😢',11),
('Adjectives','A1','tired','усталый','Needing rest','😴',12),
('Adjectives','A1','hungry','голодный','Wanting food','😋',13),
('Adjectives','A1','fast','быстрый','Moving with speed','⚡',14),
('Adjectives','A1','slow','медленный','Not moving quickly','🐢',15),
('Adjectives','A1','easy','лёгкий / простой','Not difficult','✅',16),
('Adjectives','A1','difficult','трудный / сложный','Needing much effort','❌',17),
('Adjectives','A1','clean','чистый','Free from dirt','✨',18),
('Adjectives','A1','dirty','грязный','Not clean','🪣',19),
('Adjectives','A1','beautiful','красивый','Very attractive','🌸',20),
('Adjectives','A1','ugly','некрасивый','Not attractive','😬',21),
('Adjectives','A1','free','свободный / бесплатный','Available or without cost','🆓',22),
('Adjectives','A1','busy','занятой','Having a lot to do','💼',23),
('Adjectives','A1','right','правильный / правый','Correct or the right side','✅',24),
('Adjectives','A1','wrong','неправильный','Incorrect','❌',25)

ON CONFLICT DO NOTHING;
