-- ============================================================
-- Talk2Learn - Vocabulary Cards A1 (500 ????)
-- ????: Animals, Food, Drinks, Home, Colors, Numbers,
--        Family, Body, Clothes, Weather, Time, Nature,
--        School, Transport, Places, Greetings, Actions, Adjectives
-- ??????: (topic, level, word, translation, definition, emoji_code, order_num)
-- ============================================================

INSERT INTO vocabulary_cards (topic, level, word, translation, definition, emoji_code, order_num) VALUES

-- ============================================================
-- ANIMALS (30 ????)
-- ============================================================
('Animals','A1','cat','??? / ?????','A small pet that says meow','-',1),
('Animals','A1','dog','??????','A loyal pet animal','-',2),
('Animals','A1','bird','?????','An animal with wings that can fly','-',3),
('Animals','A1','fish','????','An animal that lives in water','-',4),
('Animals','A1','horse','??????','A large animal used for riding','-',5),
('Animals','A1','cow','??????','A farm animal that gives milk','-',6),
('Animals','A1','pig','??????','A pink farm animal','-',7),
('Animals','A1','sheep','????','A farm animal with wool','-',8),
('Animals','A1','rabbit','??????','A small animal with long ears','-',9),
('Animals','A1','duck','????','A bird that swims in water','-',10),
('Animals','A1','bear','???????','A large wild animal','-',11),
('Animals','A1','lion','???','The king of the jungle','-',12),
('Animals','A1','elephant','????','A very large animal with a trunk','-',13),
('Animals','A1','monkey','????????','An animal that climbs trees','-',14),
('Animals','A1','snake','????','A long animal without legs','-',15),
('Animals','A1','frog','???????','A small green jumping animal','-',16),
('Animals','A1','tiger','????','A big wild cat with stripes','-',17),
('Animals','A1','wolf','????','A wild dog-like animal','-',18),
('Animals','A1','fox','????','A clever wild orange animal','-',19),
('Animals','A1','mouse','????','A very small animal','-',20),
('Animals','A1','chicken','??????','A farm bird we eat eggs from','-',21),
('Animals','A1','penguin','???????','A black and white bird that cannot fly','-',22),
('Animals','A1','dolphin','???????','A smart sea animal','-',23),
('Animals','A1','turtle','????????','An animal with a hard shell','-',24),
('Animals','A1','bee','?????','A yellow and black insect that makes honey','-',25),
('Animals','A1','butterfly','???????','A beautiful flying insect','-',26),
('Animals','A1','ant','???????','A very small hard-working insect','-',27),
('Animals','A1','spider','????','An eight-legged insect','-',28),
('Animals','A1','deer','?????','A wild animal with big horns','-',29),
('Animals','A1','hamster','?????','A small pet with big cheeks','-',30),

-- ============================================================
-- FOOD (35 ????)
-- ============================================================
('Food','A1','apple','??????','A round red or green fruit','-',1),
('Food','A1','banana','?????','A long yellow fruit','-',2),
('Food','A1','bread','????','A baked food made from flour','-',3),
('Food','A1','egg','????','Food from a chicken','-',4),
('Food','A1','rice','???','Small white grains we cook and eat','-',5),
('Food','A1','soup','???','Hot liquid food','-',6),
('Food','A1','pizza','?????','Italian food with cheese and toppings','-',7),
('Food','A1','burger','??????','A sandwich with a meat patty','-',8),
('Food','A1','cake','???? / ?????','A sweet baked dessert','-',9),
('Food','A1','salad','?????','A dish of mixed vegetables','-',10),
('Food','A1','cheese','???','A dairy product made from milk','-',11),
('Food','A1','butter','?????','A yellow fat made from cream','-',12),
('Food','A1','milk','??????','A white liquid from cows','-',13),
('Food','A1','orange','????????','A round orange citrus fruit','-',14),
('Food','A1','lemon','?????','A yellow sour citrus fruit','-',15),
('Food','A1','tomato','???????','A red fruit used in cooking','-',16),
('Food','A1','potato','?????????','A starchy vegetable grown underground','-',17),
('Food','A1','carrot','???????','An orange root vegetable','-',18),
('Food','A1','onion','???','A round vegetable with layers','-',19),
('Food','A1','garlic','??????','A strong-smelling white bulb','-',20),
('Food','A1','pasta','????? / ????????','Italian noodles','-',21),
('Food','A1','sandwich','?????????','Two slices of bread with filling','-',22),
('Food','A1','ice cream','?????????','A cold sweet dessert','-',23),
('Food','A1','chocolate','???????','A sweet brown food','-',24),
('Food','A1','cookie','???????','A small sweet biscuit','-',25),
('Food','A1','honey','?-?','A sweet liquid made by bees','-',26),
('Food','A1','strawberry','????????','A small red sweet fruit','-',27),
('Food','A1','grapes','????????','Small round fruits that grow in clusters','-',28),
('Food','A1','watermelon','?????','A large green fruit with red inside','-',29),
('Food','A1','mushroom','????','A fungus used in cooking','-',30),
('Food','A1','corn','????????','A yellow vegetable on a cob','-',31),
('Food','A1','pepper','?????','A spicy or sweet vegetable','-',32),
('Food','A1','cucumber','??????','A long green vegetable','-',33),
('Food','A1','meat','????','Food from animals','-',34),
('Food','A1','fish','???? (???)','Seafood eaten as a meal','-',35),

-- ============================================================
-- DRINKS (15 ????)
-- ============================================================
('Drinks','A1','water','????','A clear liquid essential for life','-',1),
('Drinks','A1','tea','???','A hot drink made with leaves','-',2),
('Drinks','A1','coffee','????','A hot dark drink','-',3),
('Drinks','A1','juice','???','A drink made from fruit','-',4),
('Drinks','A1','cola','????','A sweet fizzy dark drink','-',5),
('Drinks','A1','lemonade','???????','A sweet lemon drink','-',6),
('Drinks','A1','beer','????','An alcoholic drink made from grain','-',7),
('Drinks','A1','wine','????','An alcoholic drink made from grapes','-',8),
('Drinks','A1','smoothie','?????','A blended fruit drink','-',9),
('Drinks','A1','milkshake','???????? ????????','A thick sweet milk drink','-',10),
('Drinks','A1','hot chocolate','??????? ???????','A warm sweet cocoa drink','-',11),
('Drinks','A1','soda','?????????','A fizzy sweet drink','-',12),
('Drinks','A1','yogurt','??????','A thick dairy drink or food','-',13),
('Drinks','A1','champagne','??????????','A fizzy white wine for celebrations','-',14),
('Drinks','A1','syrup','?????','A thick sweet liquid added to drinks','-',15),

-- ============================================================
-- HOME (30 ????)
-- ============================================================
('Home','A1','house','???','A building where people live','-',1),
('Home','A1','room','???????','A space inside a building','-',2),
('Home','A1','kitchen','?????','A room for cooking','-',3),
('Home','A1','bedroom','???????','A room for sleeping','-',4),
('Home','A1','bathroom','??????','A room with a bath or shower','-',5),
('Home','A1','door','?????','An entrance to a room','-',6),
('Home','A1','window','????','A glass opening in a wall','-',7),
('Home','A1','table','????','A flat surface with legs','-',8),
('Home','A1','chair','????','Furniture for sitting','-',9),
('Home','A1','bed','???????','Furniture for sleeping','-',10),
('Home','A1','sofa','?????','A comfortable seat for several people','-',11),
('Home','A1','lamp','?????','A device that gives light','-',12),
('Home','A1','clock','????','A device that shows time','-',13),
('Home','A1','mirror','???????','A reflective surface','-',14),
('Home','A1','stairs','????????','Steps connecting floors','-',15),
('Home','A1','floor','???','The bottom surface of a room','-',16),
('Home','A1','wall','?????','A vertical surface in a room','-',17),
('Home','A1','ceiling','???????','The top surface of a room','-',18),
('Home','A1','fridge','???????????','A cold appliance for food storage','-',19),
('Home','A1','oven','???????','An appliance for baking','-',20),
('Home','A1','TV','?????????','An electronic screen for watching','-',21),
('Home','A1','phone','???????','A device for calling','-',22),
('Home','A1','computer','?????????','An electronic device for work','-',23),
('Home','A1','book','?????','Pages with writing or pictures','-',24),
('Home','A1','key','????','A metal object that opens locks','-',25),
('Home','A1','bag','?????','A container for carrying things','-',26),
('Home','A1','box','???????','A square container','-',27),
('Home','A1','cup','?????','A container for drinking','-',28),
('Home','A1','plate','???????','A flat dish for food','-',29),
('Home','A1','spoon','?????','A utensil for eating soup','-',30),

-- ============================================================
-- COLORS (15 ????)
-- ============================================================
('Colors','A1','red','???????','The color of fire and blood','-',1),
('Colors','A1','blue','????? / ???????','The color of the sky','-',2),
('Colors','A1','green','???-???','The color of grass','-',3),
('Colors','A1','yellow','?-????','The color of the sun','-',4),
('Colors','A1','orange','?????????','A warm color between red and yellow','-',5),
('Colors','A1','purple','??????????','A mix of red and blue','-',6),
('Colors','A1','pink','???????','A light red color','-',7),
('Colors','A1','black','?-????','The darkest color','-',8),
('Colors','A1','white','?????','The lightest color','-',9),
('Colors','A1','grey','?????','A color between black and white','-',10),
('Colors','A1','brown','??????????','The color of wood or chocolate','-',11),
('Colors','A1','gold','???????','A shiny yellow metallic color','-',12),
('Colors','A1','silver','??????????','A shiny grey metallic color','-',13),
('Colors','A1','light blue','??????-???????','A pale blue color','-',14),
('Colors','A1','dark green','?-???-???-???','A deep green color','-',15),

-- ============================================================
-- FAMILY (20 ????)
-- ============================================================
('Family','A1','mother','???? / ????','A female parent','-',1),
('Family','A1','father','???? / ????','A male parent','-',2),
('Family','A1','sister','??????','A female sibling','-',3),
('Family','A1','brother','????','A male sibling','-',4),
('Family','A1','grandmother','???????','Mother of your parent','-',5),
('Family','A1','grandfather','???????','Father of your parent','-',6),
('Family','A1','daughter','????','A female child','-',7),
('Family','A1','son','???','A male child','-',8),
('Family','A1','aunt','?-??','Your parent''s sister','-',9),
('Family','A1','uncle','????','Your parent''s brother','-',10),
('Family','A1','cousin','?????????? ????/??????','Child of your aunt or uncle','-',11),
('Family','A1','wife','????','A married woman','-',12),
('Family','A1','husband','???','A married man','-',13),
('Family','A1','baby','?????','A very young child','-',14),
('Family','A1','child','???-???','A young person','-',15),
('Family','A1','parents','????????','Mother and father together','-',16),
('Family','A1','family','?????','A group of related people','-',17),
('Family','A1','twins','????????','Two children born at the same time','-',18),
('Family','A1','nephew','?????????','Your sibling''s son','-',19),
('Family','A1','niece','??????????','Your sibling''s daughter','-',20),

-- ============================================================
-- BODY (25 ????)
-- ============================================================
('Body','A1','head','??????','The top part of the body','-',1),
('Body','A1','hair','??????','Strands growing on the head','-',2),
('Body','A1','eye','????','An organ used for seeing','-',3),
('Body','A1','ear','???','An organ used for hearing','-',4),
('Body','A1','nose','???','An organ used for smelling','-',5),
('Body','A1','mouth','???','Used for eating and speaking','-',6),
('Body','A1','tooth','???','A hard white structure in the mouth','-',7),
('Body','A1','tongue','????','A muscle inside the mouth','-',8),
('Body','A1','neck','???','The part connecting head and body','-',9),
('Body','A1','shoulder','?????','The top of the arm','-',10),
('Body','A1','arm','???? (?? ?????)','A limb from shoulder to hand','-',11),
('Body','A1','hand','???? (?????)','The end part of the arm','-',12),
('Body','A1','finger','?????','One of five digits on the hand','-',13),
('Body','A1','leg','????','A limb used for walking','-',14),
('Body','A1','foot','??????','The bottom of the leg','-',15),
('Body','A1','knee','??????','The joint in the middle of the leg','-',16),
('Body','A1','back','?????','The rear part of the body','-',17),
('Body','A1','stomach','?????','The front middle of the body','-',18),
('Body','A1','chest','?????','The front upper body','-',19),
('Body','A1','heart','??????','The organ that pumps blood','-',20),
('Body','A1','face','????','The front of the head','-',21),
('Body','A1','cheek','????','The soft side of the face','-',22),
('Body','A1','chin','??????????','The bottom of the face','-',23),
('Body','A1','thumb','??????? ?????','The short wide finger','-',24),
('Body','A1','nail','??????','The hard covering on a finger','-',25),

-- ============================================================
-- CLOTHES (25 ????)
-- ============================================================
('Clothes','A1','shirt','???????','A top with buttons','-',1),
('Clothes','A1','T-shirt','????????','A casual top without buttons','-',2),
('Clothes','A1','trousers','?????','Long leg-covering clothes','-',3),
('Clothes','A1','jeans','??????','Denim trousers','-',4),
('Clothes','A1','dress','??????','A one-piece garment for women','-',5),
('Clothes','A1','skirt','????','A garment worn below the waist','-',6),
('Clothes','A1','jacket','??????','An outer layer of clothing','-',7),
('Clothes','A1','coat','??????','A long warm outer garment','-',8),
('Clothes','A1','shoes','????? / ?????','Footwear for going outside','-',9),
('Clothes','A1','boots','??????','Footwear covering the ankle','-',10),
('Clothes','A1','socks','?????','Clothing for the feet','-',11),
('Clothes','A1','hat','????? / ?????','A covering for the head','-',12),
('Clothes','A1','scarf','????','A cloth worn around the neck','-',13),
('Clothes','A1','gloves','????????','Covering for hands','-',14),
('Clothes','A1','sweater','??????','A warm knitted top','-',15),
('Clothes','A1','underwear','?????? ????-','Clothes worn under other clothes','-',16),
('Clothes','A1','pyjamas','??????','Clothes worn for sleeping','-',17),
('Clothes','A1','uniform','?????','Special clothes for work or school','-',18),
('Clothes','A1','suit','??????','A formal jacket and trousers','-',19),
('Clothes','A1','tie','???????','A long piece of fabric around the neck','-',20),
('Clothes','A1','belt','??????','A strap worn around the waist','-',21),
('Clothes','A1','pocket','??????','A small bag sewn into clothing','-',22),
('Clothes','A1','button','????????','A small fastener on clothes','-',23),
('Clothes','A1','size','??????','How big or small something is','-',24),
('Clothes','A1','colour','???? (??????)','The shade of a piece of clothing','-',25),

-- ============================================================
-- WEATHER (20 ????)
-- ============================================================
('Weather','A1','sun','??????','The star that gives us light and heat','-',1),
('Weather','A1','rain','?????','Water falling from clouds','-',2),
('Weather','A1','snow','????','White frozen water falling from clouds','-',3),
('Weather','A1','cloud','??????','A white or grey mass in the sky','-',4),
('Weather','A1','wind','?????','Moving air','-',5),
('Weather','A1','storm','???? / ?????','Very bad weather with heavy rain','-',6),
('Weather','A1','thunder','????','A loud sound during a storm','-',7),
('Weather','A1','lightning','??????','A flash of light in a storm','-',8),
('Weather','A1','fog','?????','Very thick cloud near the ground','-',9),
('Weather','A1','ice','?-?','Frozen water','-',10),
('Weather','A1','rainbow','??????','Coloured arch in the sky after rain','-',11),
('Weather','A1','temperature','???????????','How hot or cold it is','-',12),
('Weather','A1','hot','?????','Very high temperature','-',13),
('Weather','A1','cold','???????','Very low temperature','-',14),
('Weather','A1','warm','?????','A comfortable pleasant temperature','-',15),
('Weather','A1','cool','?????????','Slightly cold but comfortable','-',16),
('Weather','A1','wet','?????','Covered with water','-',17),
('Weather','A1','dry','????','Without water or moisture','-',18),
('Weather','A1','sunny','????????','Bright with sunshine','-',19),
('Weather','A1','cloudy','???????','Covered with clouds','-',20),

-- ============================================================
-- TIME (20 ????)
-- ============================================================
('Time','A1','morning','????','The early part of the day','-',1),
('Time','A1','afternoon','???? / ?????????????','The middle of the day','-',2),
('Time','A1','evening','?????','The end of the day before night','-',3),
('Time','A1','night','????','The dark part of the day','-',4),
('Time','A1','today','???????','This current day','-',5),
('Time','A1','tomorrow','??????','The day after today','-',6),
('Time','A1','yesterday','?????','The day before today','-',7),
('Time','A1','week','??????','Seven days','-',8),
('Time','A1','month','?????','About 30 days','-',9),
('Time','A1','year','???','12 months','-',10),
('Time','A1','hour','???','60 minutes','-',11),
('Time','A1','minute','??????','60 seconds','-',12),
('Time','A1','second','???????','A very short time','-',13),
('Time','A1','Monday','???????????','The first day of the week','-',14),
('Time','A1','Friday','???????','The last working day','-',15),
('Time','A1','weekend','????????','Saturday and Sunday','-',16),
('Time','A1','holiday','???????? / ????????','A special day or vacation','-',17),
('Time','A1','birthday','???? ????????','The anniversary of your birth','-',18),
('Time','A1','now','??????','At this moment','-',19),
('Time','A1','late','??????','After the expected time','-',20),

-- ============================================================
-- NATURE (20 ????)
-- ============================================================
('Nature','A1','tree','??????','A tall plant with a trunk','-',1),
('Nature','A1','flower','??????','A pretty plant with petals','-',2),
('Nature','A1','grass','?????','Green plants covering the ground','-',3),
('Nature','A1','river','????','A large stream of flowing water','-',4),
('Nature','A1','sea','????','A large body of salt water','-',5),
('Nature','A1','mountain','????','A very high hill','-',6),
('Nature','A1','forest','???','A large area of trees','-',7),
('Nature','A1','beach','????','Sand next to the sea','-',8),
('Nature','A1','sky','????','The space above the earth','-',9),
('Nature','A1','star','??????','A bright object in the night sky','-',10),
('Nature','A1','moon','????','The natural satellite of Earth','-',11),
('Nature','A1','earth','?????','The ground or our planet','-',12),
('Nature','A1','sun','??????','The star in our solar system','-',13),
('Nature','A1','lake','?????','A body of water surrounded by land','-',14),
('Nature','A1','island','??????','Land surrounded by water','-',15),
('Nature','A1','desert','???????','A very dry sandy area','-',16),
('Nature','A1','rock','?????? / ?????','A hard natural material','-',17),
('Nature','A1','sand','?????','Tiny grains found on beaches','-',18),
('Nature','A1','leaf','????','The flat green part of a plant','-',19),
('Nature','A1','plant','????????','A living thing that grows in soil','-',20),

-- ============================================================
-- SCHOOL (25 ????)
-- ============================================================
('School','A1','school','?????','A place for learning','-',1),
('School','A1','teacher','???????','A person who teaches','-',2),
('School','A1','student','?????? / ???????','A person who learns','-',3),
('School','A1','class','????? / ????','A group of students or a lesson','-',4),
('School','A1','lesson','????','A period of learning','-',5),
('School','A1','book','?????','Pages bound together for reading','-',6),
('School','A1','pen','?????','A tool for writing with ink','-',7),
('School','A1','pencil','????????','A tool for writing that can be erased','-',8),
('School','A1','paper','??????','A thin material for writing','-',9),
('School','A1','notebook','???????','A book with blank pages for writing','-',10),
('School','A1','bag','???????? / ?????','A container for carrying school things','-',11),
('School','A1','desk','????? / ????','A table for working or studying','-',12),
('School','A1','board','?????','A surface for writing in class','-',13),
('School','A1','homework','???????? ???????','Work done at home for school','-',14),
('School','A1','test','???? / ???????????','An exam to check knowledge','-',15),
('School','A1','answer','?????','A reply to a question','-',16),
('School','A1','question','??????','Something you ask to get information','-',17),
('School','A1','letter','????? / ??????','A symbol in the alphabet','-',18),
('School','A1','word','?????','A unit of language','-',19),
('School','A1','number','????? / ?????','A symbol used in maths','-',20),
('School','A1','read','??????','To understand written words','-',21),
('School','A1','write','??????','To form letters or words','-',22),
('School','A1','listen','???????','To pay attention to sound','-',23),
('School','A1','speak','????????','To say words aloud','-',24),
('School','A1','understand','????????','To know the meaning','-',25),

-- ============================================================
-- TRANSPORT (20 ????)
-- ============================================================
('Transport','A1','car','??????','A vehicle with four wheels','-',1),
('Transport','A1','bus','???????','A large vehicle for many passengers','-',2),
('Transport','A1','train','?????','A vehicle that runs on rails','-',3),
('Transport','A1','plane','?????-?','A vehicle that flies','-',4),
('Transport','A1','bicycle','?????????','A two-wheeled vehicle you pedal','-',5),
('Transport','A1','taxi','?????','A car you pay to travel in','-',6),
('Transport','A1','boat','?????','A small water vehicle','-',7),
('Transport','A1','ship','???????','A large water vehicle','-',8),
('Transport','A1','motorcycle','????????','A two-wheeled motor vehicle','-',9),
('Transport','A1','truck','????????','A large vehicle for carrying goods','-',10),
('Transport','A1','tram','???????','An electric vehicle on city rails','-',11),
('Transport','A1','subway','?????','An underground train system','-',12),
('Transport','A1','helicopter','??????-?','A flying vehicle with rotating blades','-',13),
('Transport','A1','road','??????','A surface for vehicles to travel on','-',14),
('Transport','A1','street','?????','A road in a city with buildings','-',15),
('Transport','A1','station','??????? / ??????','A place where vehicles stop','-',16),
('Transport','A1','airport','????????','A place where planes land','-',17),
('Transport','A1','ticket','?????','A paper that lets you travel','-',18),
('Transport','A1','driver','????????','A person who drives a vehicle','-',19),
('Transport','A1','passenger','????????','A person travelling in a vehicle','-',20),

-- ============================================================
-- PLACES (20 ????)
-- ============================================================
('Places','A1','city','?????','A large urban area','-',1),
('Places','A1','village','???????','A small rural settlement','-',2),
('Places','A1','country','??????','A nation with its own government','-',3),
('Places','A1','shop','???????','A place to buy things','-',4),
('Places','A1','market','?????','An outdoor place to buy food','-',5),
('Places','A1','hospital','????????','A place where sick people are treated','-',6),
('Places','A1','bank','????','A place to keep or borrow money','-',7),
('Places','A1','park','????','An outdoor area for relaxing','-',8),
('Places','A1','restaurant','????????','A place to eat meals','-',9),
('Places','A1','caf-','????','A small place to drink coffee','-',10),
('Places','A1','hotel','?????????','A place to stay when travelling','-',11),
('Places','A1','library','??????????','A place with books to borrow','-',12),
('Places','A1','museum','?????','A place with historical objects','-',13),
('Places','A1','cinema','?????????','A place to watch films','-',14),
('Places','A1','church','???????','A place of worship','-',15),
('Places','A1','office','????','A place where people work','-',16),
('Places','A1','factory','?????','A building where things are made','-',17),
('Places','A1','farm','?????','A place where food is grown','-',18),
('Places','A1','zoo','???????','A place with animals to visit','-',19),
('Places','A1','gym','????????','A place for exercise','-',20),

-- ============================================================
-- GREETINGS & PHRASES (20 ????)
-- ============================================================
('Greetings','A1','hello','?????? / ????????????','A common greeting','-',1),
('Greetings','A1','goodbye','???? / ?? ????????','Said when leaving','-',2),
('Greetings','A1','please','??????????','Used to make polite requests','-',3),
('Greetings','A1','thank you','???????','Said to show gratitude','-',4),
('Greetings','A1','sorry','???????? / ????????','Said to apologise','-',5),
('Greetings','A1','yes','??','A positive answer','-',6),
('Greetings','A1','no','???','A negative answer','-',7),
('Greetings','A1','OK','?????? / ?????','Showing agreement','-',8),
('Greetings','A1','help','?????? / ????????','Asking for assistance','-',9),
('Greetings','A1','welcome','????? ??????????','A greeting to guests','-',10),
('Greetings','A1','good morning','?????? ????','A morning greeting','-',11),
('Greetings','A1','good night','????????? ????','Said before sleeping','-',12),
('Greetings','A1','how are you','??? ????','Asking about someone''s wellbeing','-',13),
('Greetings','A1','nice to meet you','??????? ?????????????','Said when meeting someone new','-',14),
('Greetings','A1','excuse me','????????','Used to get attention','-',15),
('Greetings','A1','I don''t understand','? ?? ???????','Said when confused','-',16),
('Greetings','A1','can you help me','?? ?????? ??????','Asking for help','-',17),
('Greetings','A1','what is your name','??? ??? ?????','Asking someone''s name','-',18),
('Greetings','A1','my name is','???? ?????','Introducing yourself','-',19),
('Greetings','A1','see you later','?? ???????','Informal goodbye','-',20),

-- ============================================================
-- ACTIONS / VERBS (30 ????)
-- ============================================================
('Actions','A1','eat','???? / ??????','To put food in your mouth','-',1),
('Actions','A1','drink','????','To consume liquid','-',2),
('Actions','A1','sleep','?????','To rest with eyes closed','-',3),
('Actions','A1','walk','?????? / ??????','To move on foot','-',4),
('Actions','A1','run','?????? / ??????','To move fast on foot','-',5),
('Actions','A1','sit','??????','To rest on a seat','-',6),
('Actions','A1','stand','??????','To be upright on your feet','-',7),
('Actions','A1','look','????????','To direct your eyes at something','-',8),
('Actions','A1','see','??????','To perceive with eyes','-',9),
('Actions','A1','hear','???????','To perceive with ears','-',10),
('Actions','A1','speak','????????','To say words','-',11),
('Actions','A1','say','???????','To express in words','-',12),
('Actions','A1','come','?????????','To move towards a place','-',13),
('Actions','A1','go','???? / ?????','To move away from a place','-',14),
('Actions','A1','open','?????????','To make something not closed','-',15),
('Actions','A1','close','?????????','To make something shut','-',16),
('Actions','A1','buy','????????','To get something with money','-',17),
('Actions','A1','give','??????','To hand something to someone','-',18),
('Actions','A1','take','?????','To receive or pick up','-',19),
('Actions','A1','make','?????? / ????????','To create or produce','-',20),
('Actions','A1','like','????????? / ??????','To enjoy something','-',21),
('Actions','A1','want','??????','To desire something','-',22),
('Actions','A1','need','????????? / ?????','To require something','-',23),
('Actions','A1','work','????????','To do a job','-',24),
('Actions','A1','play','??????','To have fun','-',25),
('Actions','A1','read','??????','To understand text','-',26),
('Actions','A1','write','??????','To form letters','-',27),
('Actions','A1','watch','???????? (??)','To observe something attentively','-',28),
('Actions','A1','cook','????????','To prepare food with heat','-',29),
('Actions','A1','clean','??????? / ???????','To make something tidy','-',30),

-- ============================================================
-- ADJECTIVES (25 ????)
-- ============================================================
('Adjectives','A1','big','???????','Of large size','-',1),
('Adjectives','A1','small','?????????','Of little size','-',2),
('Adjectives','A1','tall','???????','Of great height','-',3),
('Adjectives','A1','short','???????? / ??????','Not long or tall','-',4),
('Adjectives','A1','long','???????','Of great length','-',5),
('Adjectives','A1','new','?????','Recently made or bought','-',6),
('Adjectives','A1','old','??????','Having existed for a long time','-',7),
('Adjectives','A1','good','???????','Of high quality','-',8),
('Adjectives','A1','bad','??????','Of low quality','-',9),
('Adjectives','A1','happy','??????????','Feeling pleased','-',10),
('Adjectives','A1','sad','????????','Feeling unhappy','-',11),
('Adjectives','A1','tired','???????','Needing rest','-',12),
('Adjectives','A1','hungry','????????','Wanting food','-',13),
('Adjectives','A1','fast','???????','Moving with speed','-',14),
('Adjectives','A1','slow','?????????','Not moving quickly','-',15),
('Adjectives','A1','easy','?-???? / ???????','Not difficult','-',16),
('Adjectives','A1','difficult','??????? / ???????','Needing much effort','-',17),
('Adjectives','A1','clean','??????','Free from dirt','-',18),
('Adjectives','A1','dirty','???????','Not clean','-',19),
('Adjectives','A1','beautiful','????????','Very attractive','-',20),
('Adjectives','A1','ugly','??????????','Not attractive','-',21),
('Adjectives','A1','free','????????? / ??????????','Available or without cost','-',22),
('Adjectives','A1','busy','???????','Having a lot to do','-',23),
('Adjectives','A1','right','?????????? / ??????','Correct or the right side','-',24),
('Adjectives','A1','wrong','????????????','Incorrect','-',25)

ON CONFLICT DO NOTHING;
